name: docker-build-workflow

on: [push]

jobs:
  build-container:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps: 
      - uses: actions/checkout@v3
    
      - name: Build the Docker image
        working-directory: 03-app-dotnet
        run: docker build . --file Dockerfile --tag my-app-by-docker:$(date +%s)
