name: docker-build-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps: 
      - uses: actions/demo-test-actions
      - name: Build the Docker image        
        run: docker build . --tag my-app-by-docker:$(date +%s)
